/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ubp.doo.vista;

import edu.ubp.doo.controlador.Controlador;
import java.awt.event.ActionEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agustin
 */
public class FrmAbmMateria extends javax.swing.JDialog implements InterfazVistaAbm {

    private static final long serialVersionUID = 1L;
    private final DefaultTableModel modeloTbl;
    /**
     * Creates new form FrmAbmMateria
     * @param parent
     * @param modal
     */
    public FrmAbmMateria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.modeloTbl = (DefaultTableModel) this.tblMaterias.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpEdicion = new javax.swing.JPopupMenu();
        mItemNuevo = new javax.swing.JMenuItem();
        mItemGuardar = new javax.swing.JMenuItem();
        mItemModificar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JFormattedTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnEdicion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTotalFilasTabla = new javax.swing.JLabel();

        mItemNuevo.setText("Nuevo");
        mItemNuevo.setActionCommand("LIMPIAR");
        popUpEdicion.add(mItemNuevo);

        mItemGuardar.setText("Guardar");
        mItemGuardar.setActionCommand("GUARDAR");
        mItemGuardar.setEnabled(false);
        popUpEdicion.add(mItemGuardar);

        mItemModificar.setText("Modificar");
        mItemModificar.setActionCommand("MODIFICAR");
        mItemModificar.setEnabled(false);
        popUpEdicion.add(mItemModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Materias");
        setResizable(false);

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMaterias);

        btnEliminar.setText("Eliminar Seleccion");
        btnEliminar.setActionCommand("ELIMINAR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar"));

        jLabel1.setText("Id:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        try {
            txtId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtId.setEnabled(false);

        btnEdicion.setText("Edicion");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setActionCommand("LIMPIAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnEdicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdicion)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        lblTotalFilasTabla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalFilasTabla.setText("Total filas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalFilasTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalFilasTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setControlador(Controlador c) {
        this.btnLimpiar.addActionListener(c);
        this.btnEliminar.addActionListener(c);
        this.btnEdicion.addMouseListener(c);
        this.mItemGuardar.addActionListener(c);
        this.mItemModificar.addActionListener(c);
        this.mItemNuevo.addActionListener(c);
        this.txtId.addKeyListener(c);
        this.tblMaterias.addMouseListener(c);
        c.actionPerformed(new ActionEvent(this, 0, InterfazVistaAbm.Operacion.CARGAR.toString()));
        this.lblTotalFilasTabla.setText("Total filas: " + this.modeloTbl.getRowCount());
    }

    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void imprimeMensaje(Exception... e) {
        if (e.length > 0) {
            JOptionPane.showMessageDialog(this, "Error: " + e[0].getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Operación ejecutada con exito", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    @Override
    public void limpiaVista() {
        this.txtId.setValue(null);
        this.txtDescripcion.setText("");
        this.txtNombre.setText("");
        this.tblMaterias.clearSelection();
    }

    @Override
    public void actualizaTabla(Controlador c) {
        c.actionPerformed(new ActionEvent(this, 0, InterfazVistaAbm.Operacion.CARGAR.toString()));
        this.lblTotalFilasTabla.setText("Total filas: " + this.modeloTbl.getRowCount());
    }

    public DefaultTableModel getModeloTbl() {
        return modeloTbl;
    }

    public void setTblAlumnos(javax.swing.JTable tblMaterias) {
        this.tblMaterias = tblMaterias;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdicion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalFilasTabla;
    private javax.swing.JMenuItem mItemGuardar;
    private javax.swing.JMenuItem mItemModificar;
    private javax.swing.JMenuItem mItemNuevo;
    private javax.swing.JPopupMenu popUpEdicion;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(javax.swing.JTextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public javax.swing.JFormattedTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(javax.swing.JFormattedTextField txtId) {
        this.txtId = txtId;
    }

    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(javax.swing.JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public javax.swing.JTable getTblMaterias() {
        return tblMaterias;
    }

    public void setTblMaterias(javax.swing.JTable tblMaterias) {
        this.tblMaterias = tblMaterias;
    }

    public javax.swing.JPopupMenu getPopUpEdicion() {
        return popUpEdicion;
    }

    public void setPopUpEdicion(javax.swing.JPopupMenu popUpEdicion) {
        this.popUpEdicion = popUpEdicion;
    }

    public javax.swing.JMenuItem getmItemModificar() {
        return mItemModificar;
    }

    public void setmItemModificar(javax.swing.JMenuItem mItemModificar) {
        this.mItemModificar = mItemModificar;
    }

    public javax.swing.JMenuItem getmItemGuardar() {
        return mItemGuardar;
    }

    public void setmItemGuardar(javax.swing.JMenuItem mItemGuardar) {
        this.mItemGuardar = mItemGuardar;
    }

}
