/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ubp.doo.vista;

import edu.ubp.doo.controlador.Controlador;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agustin
 */
public class FrmAbmInscripcion extends javax.swing.JDialog implements InterfazVistaAbm {

    private static final long serialVersionUID = 1L;
    private final DefaultTableModel modeloTbl;

    /**
     * Creates new form FrmBmInscripcion
     *
     * @param parent
     * @param modal
     */
    public FrmAbmInscripcion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.modeloTbl = (DefaultTableModel) this.tblInscripciones.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInscripciones = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        lblTotalFilasTabla = new javax.swing.JLabel();
        btnInscribir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Alumno", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInscripciones);

        btnEliminar.setText("Eliminar Seleccion");
        btnEliminar.setActionCommand("ELIMINAR");

        lblTotalFilasTabla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalFilasTabla.setText("Total filas:");

        btnInscribir.setText("Inscribir");
        btnInscribir.setActionCommand("INSCRIBIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalFilasTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscribir))
                    .addComponent(lblTotalFilasTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setControlador(Controlador c) {
        this.btnEliminar.addActionListener(c);
        this.btnInscribir.addActionListener(c);
        this.tblInscripciones.addMouseListener(c);
        c.actionPerformed(new ActionEvent(this, 0, InterfazVistaAbm.Operacion.CARGAR.toString()));
        this.lblTotalFilasTabla.setText("Total filas: " + this.modeloTbl.getRowCount());
    }

    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void imprimeMensaje(Exception... e) {
        if (e.length > 0) {
            JOptionPane.showMessageDialog(this, "Error: " + e[0].getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Operación ejecutada con exito", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    @Override
    public void limpiaVista() {
        this.tblInscripciones.clearSelection();
    }

    @Override
    public void actualizaTabla(Controlador c) {
        c.actionPerformed(new ActionEvent(this, 0, InterfazVistaAbm.Operacion.CARGAR.toString()));
        this.lblTotalFilasTabla.setText("Total filas: " + this.modeloTbl.getRowCount());
    }

    public DefaultTableModel getModeloTbl() {
        return modeloTbl;
    }

    public javax.swing.JTable getTblInscripciones() {
        return tblInscripciones;
    }

    public void setTblInscripciones(javax.swing.JTable tblInscripciones) {
        this.tblInscripciones = tblInscripciones;
    }

    public javax.swing.JLabel getLblTotalFilasTabla() {
        return lblTotalFilasTabla;
    }

    public void setLblTotalFilasTabla(javax.swing.JLabel lblTotalFilasTabla) {
        this.lblTotalFilasTabla = lblTotalFilasTabla;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalFilasTabla;
    private javax.swing.JTable tblInscripciones;
    // End of variables declaration//GEN-END:variables
}
